site_name: Grim's Cutscene Engine Documentation
site_url: https://reapimus.github.io/grims-cutscene-engine/
repo_name: Reapimus/grims-cutscene-engine
repo_url: https://github.com/Reapimus/grims-cutscene-engine

theme:
  name: material
  palette:
    scheme: slate
    primary: red
    accent: red

nav:
  - Home: index.md
  - Guide:
    - Installation: guide/installation.md
    - Interface: guide/interface.md
    - Subtitles: guide/subtitles.md
    - Actions: guide/actions.md
  - API Reference: api-reference.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.superfences